---

sudo: required
dist: trusty
language: python
services:
  - docker

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING=False
  matrix:
    - TEST_OSVER="debian:7"
    - TEST_OSVER="debian:8"
    - TEST_OSVER="ubuntu:1404"
    - TEST_OSVER="centos:6"
    - TEST_OSVER="centos:7"

install:
  # Download ansible-role-tester and setup the enviroment
  - wget http://s3.gibbsoft.com/travisci/test.sh
  - chmod +x test.sh

script:
  - ./test.sh $TEST_OSVER
